# syntax=docker/dockerfile:1

FROM ubuntu:20.04

EXPOSE 81
WORKDIR /opt/app 
COPY web-db/flask_app .
RUN apt-get update && \
     apt-get install -y libmysqlclient-dev && \
     apt-get install -y python3 && \
     apt-get install -y python3-pip

RUN pip3 install -r requirements.txt

CMD ["python3", "app.py"]